const colors = {
  light: {
    text: "#0D1117",
    tint: "#00AEEF",
    background: "#F5F7FA",
    foreground: "#0D1117",
    card: "#FFFFFF",
    cardForeground: "#0D1117",
    primary: "#00AEEF",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F4FD",
    secondaryForeground: "#0D1117",
    muted: "#EDF0F5",
    mutedForeground: "#6B7A8D",
    accent: "#00AEEF",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDE3EC",
    input: "#DDE3EC",
    success: "#22C55E",
    warning: "#F59E0B",
    overlay: "rgba(0,0,0,0.45)",
    floatingBg: "#FFFFFF",
    floatingBorder: "#00AEEF",
    statusBar: "dark-content" as const,
  },
  dark: {
    text: "#E8EDF5",
    tint: "#00AEEF",
    background: "#0D1117",
    foreground: "#E8EDF5",
    card: "#161B22",
    cardForeground: "#E8EDF5",
    primary: "#00AEEF",
    primaryForeground: "#0D1117",
    secondary: "#1C2433",
    secondaryForeground: "#E8EDF5",
    muted: "#1C2433",
    mutedForeground: "#8B96A8",
    accent: "#00AEEF",
    accentForeground: "#0D1117",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#21262D",
    input: "#21262D",
    success: "#22C55E",
    warning: "#F59E0B",
    overlay: "rgba(0,0,0,0.65)",
    floatingBg: "#161B22",
    floatingBorder: "#00AEEF",
    statusBar: "light-content" as const,
  },
  radius: 14,
};

export default colors;
